name: Java Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag a ejecutar (por ejemplo @smoke, @regression)'
        required: false
jobs:
  ExecuteTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20.0.1'
          distribution: 'temurin'
          cache: maven

      - name: Instalar Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install"

      - name: Build with Maven
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            mvn clean test -PGrid -DtagExecution=${{ github.event.inputs.tag }}
          else
            mvn clean test -PGrid
          fi
      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --unsafe-perm=true
          allure generate target/cucumber-reports/ --clean -o target/allure-report

      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cucumber Reports
          path: target/cucumber-reports

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure Reports
          path: target/allure-report
