name: Java Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag a ejecutar (por ejemplo @smoke, @regression)'
        required: false
        default: '@smoke'
jobs:
  ExecuteTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20.0.1'
          distribution: 'temurin'
          cache: maven

      - name: Instalar Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install"

      - name: Build with Maven
        run: mvn clean test -PGrid -DtagExecution=${{ github.event.inputs.tag }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cucumber Reports
          path: target/Reports
