name: Deploy Allure Report to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '20.0.1'
          distribution: 'temurin'

      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install"

      - name: Run Tests and Generate Allure Report
        run: |
          mvn clean test -PGrid
          npm install -g allure-commandline --unsafe-perm=true
          allure generate target/allure-results --clean -o target/allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
